lemma and_or_distrib_left (P Q R : Prop) : P ∧ (Q ∨ R) ↔ (P ∧ Q) ∨ (P ∧ R) :=
begin
    split,
    intro fpqr,
    cases fpqr with p qr,
    cases qr with q r,
    have pq : P ∧ Q,
    split,
    exact p,
    exact q,
    left,
    exact pq,
    have pr : P ∧ R,
    split,
    exact p,
    exact r,
    right,
    exact pr,

    intro fpqpr,
    split,
    cases fpqpr with pq pr,
    cases pq with p q,
    exact p,
    cases pr with p r,
    exact p,
    cases fpqpr with pq pr,
    cases pq with p q,
    left,
    exact q,
    cases pr with p r,
    right,
    exact r,
end